version: "3.3"
services:
       nginx: 
            build:
              dockerfile: Dockerfile
              context: ./nginx
            image: tonycook/property-app-nginx
            ports:
              - "80:80"
       client:
            build:
              context: ./client
              dockerfile: Dockerfile
            image: tonycook/property-app-client
            # ports:
            #   - "3000:3000"
            container_name: client
       api:        
           build:
              context: ./server
              dockerfile: Dockerfile
           image: tonycook/property-app-api
          #  ports:
          #    - "3001:3001"
           container_name: api
           environment:
             - PORT=3001


